version: '2'

services:
  db_mysql:
    image: mysql:5.6
    container_name: pece-db-mysql
    network_mode: bridge
    environment:
      - MYSQL_USER=pece
      - MYSQL_DATABASE=pece
      - MYSQL_PASSWORD=ZwTuVZzQO90qwYzA
      - MYSQL_ROOT_PASSWORD=Sk82jxYqqpx02jxT
    volumes:
      - ../databases/pece:/var/lib/mysql

  dev_pece:
    image: taller/pece
    hostname: "dev"
    network_mode: bridge
    working_dir: /pece/drupal
    volumes:
      - ./:/pece/drupal
      - ./docker/pece.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/fastcgi.conf:/etc/nginx/fastcgi.conf
    container_name: pece-dev-apache
    build:
      context: ./
      dockerfile: ./docker/DockerfileDevelopment
    links:
      - db_mysql:pece-db
