---
- name: Check if the project is already cloned.
  stat: "path={{ drupal_project_path }}/.git"
  register: drupal_project_cloned_status

- name: Download Drupal from Git repository. This may take a few minutes...
  git: >
    repo={{ drupal_source }}
    version={{ drupal_project_branch }}
    accept_hostkey=yes
    dest={{ drupal_project_path }}
  register: drupal_project_cloned_status
  when: drupal_project_cloned_status.stat.exists == false