site_name: PECE Documentation
nav:
   - Home: index.md
   - About PECE: about.md
   - Getting Started: gettingstarted.md
   - Installing and Administering PECE: installation.md
   - Users' Guide: usersguide.md
   - Data Management: datamanagement.md
   - Legal Documents: legal.md
   - Contributors' Guide: contributors.md
theme: readthedocs
