---
  - src: geerlingguy.drush
  - src: geerlingguy.git
  - src: geerlingguy.java
  - src: geerlingguy.mysql
  - src: geerlingguy.solr
  - src: geerlingguy.tomcat6
  - src: jdauphant.nginx
  - src: laggyluke.direnv
  - src: laggyluke.nodejs-app
  - src: https://github.com/NBZ4live/ansible-php-fpm
    version: master
    name: nbz4live.php-fpm
  - src: pbuyle.nginx-drupal
  - src: kosssi.composer
  - src: revagomes.php-pecl
  - src: revagomes.phpsh
